name: flame_camera_tools
description: "Inituitive camera management for Flame."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0

dev_dependencies:
  flutter_lints: ^5.0.0
