name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+(\+[\d]+)?'
    branches:
      - 'master'

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: .